"""Initial migration - create all tables

Revision ID: 02a40d4dde96
Revises: 
Create Date: 2025-10-06 23:30:08.134876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a40d4dde96'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=True)
    op.create_table('values_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('chosen_value', sa.String(length=255), nullable=False),
    sa.Column('chat_mode', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_sessions_id'), 'values_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_values_sessions_session_id'), 'values_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_values_sessions_user_id'), 'values_sessions', ['user_id'], unique=False)
    op.create_table('app_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('session_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_sessions_id'), 'app_sessions', ['id'], unique=False)
    op.create_table('user_apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('app_name', sa.String(length=50), nullable=False),
    sa.Column('first_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_apps_id'), 'user_apps', ['id'], unique=False)
    op.create_table('values_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_summary', sa.Boolean(), nullable=True),
    sa.Column('has_action_chips', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('message_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['values_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_values_chat_messages_id'), 'values_chat_messages', ['id'], unique=False)
    op.create_table('values_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('chat_history', sa.JSON(), nullable=True),
    sa.Column('reflection_history', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['values_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_values_summaries_id'), 'values_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_values_summaries_id'), table_name='values_summaries')
    op.drop_table('values_summaries')
    op.drop_index(op.f('ix_values_chat_messages_id'), table_name='values_chat_messages')
    op.drop_table('values_chat_messages')
    op.drop_index(op.f('ix_user_apps_id'), table_name='user_apps')
    op.drop_table('user_apps')
    op.drop_index(op.f('ix_app_sessions_id'), table_name='app_sessions')
    op.drop_table('app_sessions')
    op.drop_index(op.f('ix_values_sessions_user_id'), table_name='values_sessions')
    op.drop_index(op.f('ix_values_sessions_session_id'), table_name='values_sessions')
    op.drop_index(op.f('ix_values_sessions_id'), table_name='values_sessions')
    op.drop_table('values_sessions')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
