"""Add HD calculation system fields

Revision ID: 05d25610a124
Revises: 221d2264d089
Create Date: 2025-10-15 17:01:27.208762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d25610a124'
down_revision: Union[str, Sequence[str], None] = '221d2264d089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hd_sessions', sa.Column('zodiac_system', sa.String(length=20), nullable=True))
    op.add_column('hd_sessions', sa.Column('calculation_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hd_sessions', 'calculation_method')
    op.drop_column('hd_sessions', 'zodiac_system')
    # ### end Alembic commands ###
