"""add_spiral_tables_final

Revision ID: 0807121e47d2
Revises: b5f563dc2882
Create Date: 2025-10-19 19:27:28.096344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0807121e47d2'
down_revision: Union[str, Sequence[str], None] = 'b5f563dc2882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiral_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('initial_problem', sa.Text(), nullable=True),
    sa.Column('current_cycle', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spiral_sessions_id'), 'spiral_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_spiral_sessions_session_id'), 'spiral_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_spiral_sessions_user_id'), 'spiral_sessions', ['user_id'], unique=False)
    op.create_table('spiral_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=True),
    sa.Column('has_action_chips', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('message_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['spiral_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spiral_chat_messages_id'), 'spiral_chat_messages', ['id'], unique=False)
    op.create_table('spiral_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('summary_content', sa.Text(), nullable=False),
    sa.Column('insights', sa.JSON(), nullable=True),
    sa.Column('cycles_completed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['spiral_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_spiral_summaries_id'), 'spiral_summaries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spiral_summaries_id'), table_name='spiral_summaries')
    op.drop_table('spiral_summaries')
    op.drop_index(op.f('ix_spiral_chat_messages_id'), table_name='spiral_chat_messages')
    op.drop_table('spiral_chat_messages')
    op.drop_index(op.f('ix_spiral_sessions_user_id'), table_name='spiral_sessions')
    op.drop_index(op.f('ix_spiral_sessions_session_id'), table_name='spiral_sessions')
    op.drop_index(op.f('ix_spiral_sessions_id'), table_name='spiral_sessions')
    op.drop_table('spiral_sessions')
    # ### end Alembic commands ###
