"""add active gates to hd sessions

Revision ID: 18c92633fb88
Revises: 05d25610a124
Create Date: 2025-10-16 17:28:41.889297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c92633fb88'
down_revision: Union[str, Sequence[str], None] = '05d25610a124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hd_sessions', sa.Column('active_gates', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hd_sessions', 'active_gates')
    # ### end Alembic commands ###
