"""make_chosen_value_nullable

Revision ID: 3467a26dd0ab
Revises: 02a40d4dde96
Create Date: 2025-10-07 13:38:51.004913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3467a26dd0ab'
down_revision: Union[str, Sequence[str], None] = '02a40d4dde96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
